//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorAudit.Context.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorEntryError
    {
        public int Id { get; set; }
        public int ErrorEntryId { get; set; }
        public int ErrorId { get; set; }
    }
}
