//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorAudit.Context.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outcome
    {
        public int Id { get; set; }
        public string OutcomeDescription { get; set; }
        public string OutcomeCode { get; set; }
    }
}
